### ISSUE TITLE
Don't know how to build task 'test:benchmark'

### ISSUE THREAD

**Issue by kimquy** [rails/rails-perftest#26]
`rake test:benchmark` is not available for Rails >= 4.1.7. Not sure anyone got chance to fix it yet?

**Comment by TheAustinSeven** [comment]
there is currently a PR in review that fixes this. #25

**Comment by kimquy** [comment]
@TheAustinSeven thanks! however your solution seem doesn't work.

**Comment by TheAustinSeven** [comment]
That is strange. It worked perfectly fine when I tested it. If you are talking about the CI failure, that is not due to the code I wrote, but an error with the CI itself. Could you clarify how it doesn't work?

**Comment by senny** [comment]
@kimquy can you please post the complete backtrace of your error?

**Comment by kimquy** [comment]
@senny 
```ruby
$ bundle exec rake test:benchmark --trace
rake aborted!
Don't know how to build task 'test:benchmark'
/Users/dev/Desktop/squar/squar-server/vendor/bundle/ruby/2.0.0/gems/rake-10.3.2/lib/rake/task_manager.rb:62:in `[]'
/Users/dev/Desktop/squar/squar-server/vendor/bundle/ruby/2.0.0/gems/rake-10.3.2/lib/rake/application.rb:149:in `invoke_task'
/Users/dev/Desktop/squar/squar-server/vendor/bundle/ruby/2.0.0/gems/rake-10.3.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/Users/dev/Desktop/squar/squar-server/vendor/bundle/ruby/2.0.0/gems/rake-10.3.2/lib/rake/application.rb:106:in `each'
/Users/dev/Desktop/squar/squar-server/vendor/bundle/ruby/2.0.0/gems/rake-10.3.2/lib/rake/application.rb:106:in `block in top_level'
/Users/dev/Desktop/squar/squar-server/vendor/bundle/ruby/2.0.0/gems/rake-10.3.2/lib/rake/application.rb:115:in `run_with_threads'
/Users/dev/Desktop/squar/squar-server/vendor/bundle/ruby/2.0.0/gems/rake-10.3.2/lib/rake/application.rb:100:in `top_level'
/Users/dev/Desktop/squar/squar-server/vendor/bundle/ruby/2.0.0/gems/rake-10.3.2/lib/rake/application.rb:78:in `block in run'
/Users/dev/Desktop/squar/squar-server/vendor/bundle/ruby/2.0.0/gems/rake-10.3.2/lib/rake/application.rb:176:in `standard_exception_handling'
/Users/dev/Desktop/squar/squar-server/vendor/bundle/ruby/2.0.0/gems/rake-10.3.2/lib/rake/application.rb:75:in `run'
/Users/dev/Desktop/squar/squar-server/vendor/bundle/ruby/2.0.0/gems/rake-10.3.2/bin/rake:33:in `<top (required)>'
/Users/dev/Desktop/squar/squar-server/vendor/bundle/ruby/2.0.0/bin/rake:23:in `load'
/Users/dev/Desktop/squar/squar-server/vendor/bundle/ruby/2.0.0/bin/rake:23:in `<main>'
```

**Comment by senny** [comment]
Did you add `gem 'rails-perftest'` only in the `:test` group? For the rake tasks to be available it needs to be loaded outside the test context as well.

**Comment by kimquy** [comment]
My Gemfile
```ruby
....
gem 'rake', '10.4.2'
...
group :test do
  gem 'factory_girl_rails'
  gem 'shoulda-matchers', require: false
  gem 'capybara', require: false
  gem 'simplecov', '~> 0.9', require: false
  gem 'test_after_commit'
  gem 'rails-perftest'
  gem 'ruby-prof'
end
```

**Comment by TheAustinSeven** [comment]
You will have to move `gem 'rails-perftest'` outside of the `group :test` block

**Comment by kimquy** [comment]
@TheAustinSeven worked! Not even sure why I did try to put it outside of `group :test` Thanks!
